#!/usr/bin/env bash 

filename="null".`date +%d_%m_%y`.org
[ -z $1 ] || \
    filename=$1.`date +%d_%m_%y`.org

cat <<EOF > ${filename}
#-*- mode: org -*-
#+STARTUP: showall

                            *UNCLASSIFIED*
* Legend
  - X - done
  - + - postponed
  - ! - attention 
  - F - remove or strikethrough

# -------------------------------------------------------------------
# TODO - Description - [ ]
# -------------------------------------------------------------------

# -------------------------------------------------------------------
# NOTES
# -------------------------------------------------------------------

                            *UNCLASSIFIED*
EOF
